# Generated by Django 3.2.8 on 2021-10-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_of_execution',
            field=models.DateTimeField(blank=True, verbose_name='Дата исполнения'),
        ),
    ]
