# Generated by Django 3.2.8 on 2021-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211011_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_of_execution',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Дата исполнения'),
        ),
    ]
